services:
  - type: web
    name: restro-saas
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Restro SAAS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:lvSo0CYqLjM/k7J8YD2t1HA7P06DHbeFoiTmDdrKB+4=
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
